### ISSUE TITLE
NPE when trying to start a cal

### ISSUE THREAD

**Issue by agilob** [LibreSignal/LibreSignal#48]
```
java.lang.NullPointerException
    at android.media.MediaPlayer.start(MediaPlayer.java:1105)
    at org.thoughtcrime.redphone.audio.OutgoingRinger.onPrepared(OutgoingRinger.java:141)
    at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2156)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:153)
    at android.app.ActivityThread.main(ActivityThread.java:5071)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
    at dalvik.system.NativeStart.main(Native Method)
```

### Steps to reproduce
- sometimes (1/3) when I try to make a call it fails with NPE

### Device info

**Device:** LG
**Android version:** 4.1.2
**Signal version:** 3.21.3-websocket

**Comment by mimi89999** [comment]
#10

**Comment by mimi89999** [comment]
@agilob 
> sometimes (1/3) when I try to make a call it fails with NPE

In the other cases does it fail without NPE or actually work (I would be surprised if it does work).

**Comment by agilob** [comment]
In other cases I get error message "login failed".

**Comment by mimi89999** [comment]
The thing to do would be to remove the dialer icon because we can't get voice calls to work... Anyway, I abandoned LS. You should consider switching to Conversations or Ring.

**Comment by agilob** [comment]
Sorry to hear that.

On daily basis, I use Riot.im, there are other fundamental problems with Conversations and Ring and how they work.

**Comment by mimi89999** [comment]
@agilob 
> there are other fundamental problems with Conversations

What are the problems with Conversations?

**Comment by agilob** [comment]
XMPP, problems syncing messages between devices... key exchange between clients...

**Comment by mimi89999** [comment]
@agilob
MAM helps for the first one. As for the second one, you need to use OMEMO encryption.
